import {
  Sparkles,
  User,
  Smile,
  Award,
  Briefcase,
  Rocket,
  Building2,
  Users,
  Shield,
  Crown,
  Gamepad2,
  Flame,
  BookOpen,
  Music,
  Globe,
  Cpu,
  Heart,
  Store,
  Utensils,
  Coffee,
  Compass,
  MapPin,
  Hash,
  Dumbbell,
  Shirt,
  Sword,
  Radio,
  Terminal,
  Tv,
  Mic,
  LucideIcon
} from "lucide-react";

export interface ToolConfig {
  id: string;
  name: string;
  path: string;
  description: string;
  icon: LucideIcon;
  platforms: string[];
  styles: string[];
  defaultPlatform: string;
  defaultStyle: string;
  placeholder: string;
  resultLabel: string;
  generateButtonText: string;
}

export const tools: ToolConfig[] = [
  {
    id: "username",
    name: "Username Generator",
    path: "/username-generator",
    description: "Create memorable, platform-compliant usernames for social media and games.",
    icon: Sparkles,
    platforms: ["Universal", "Instagram", "TikTok", "YouTube", "Discord", "Twitch", "Roblox", "Gaming"],
    styles: ["Cool", "Aesthetic", "Minimal", "Luxury", "Funny", "Dark", "Cute", "Creator", "Influencer", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Cool",
    placeholder: "e.g. ghost, velvet",
    resultLabel: "Username",
    generateButtonText: "Generate 50 Usernames"
  },
  {
    id: "display-name",
    name: "Display Name Generator",
    path: "/display-name-generator",
    description: "Generate creative, eye-catching profile names for Discord, Roblox, and TikTok.",
    icon: User,
    platforms: ["Universal", "Discord", "YouTube", "TikTok", "Instagram", "Twitch", "Roblox"],
    styles: ["Cool", "Aesthetic", "Gaming", "Professional", "Funny", "Cute", "Dark", "Luxury", "Minimal"],
    defaultPlatform: "Universal",
    defaultStyle: "Cool",
    placeholder: "e.g. shadow, angel",
    resultLabel: "Display Name",
    generateButtonText: "Generate 50 Display Names"
  },
  {
    id: "nickname",
    name: "Nickname Generator",
    path: "/nickname-generator",
    description: "Find cute, short, or funny nickname ideas for friends, family, or gaming.",
    icon: Smile,
    platforms: ["Universal", "Cute", "Gaming", "Friends", "Baby Boy", "Baby Girl"],
    styles: ["Cute", "Cool", "Funny", "Short", "Aesthetic", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Cute",
    placeholder: "e.g. bub, honey",
    resultLabel: "Nickname",
    generateButtonText: "Generate 50 Nicknames"
  },
  {
    id: "brand-name",
    name: "Brand Name Generator",
    path: "/brand-name-generator",
    description: "Engineer unique, high-retention brand name ideas for your new venture or blog.",
    icon: Award,
    platforms: ["Universal", "Modern", "Tech", "Fashion", "Fitness", "Food", "Creative"],
    styles: ["Minimal", "Luxury", "Cool", "Professional", "Aesthetic", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Minimal",
    placeholder: "e.g. flow, peak",
    resultLabel: "Brand Name",
    generateButtonText: "Generate 50 Brand Names"
  },
  {
    id: "business-name",
    name: "Business Name Generator",
    path: "/business-name-generator",
    description: "Generate catchy, professional, and corporate-ready company names instantly.",
    icon: Briefcase,
    platforms: ["Universal", "Agency", "Consulting", "Finance", "Logistics", "Tech", "Creative"],
    styles: ["Professional", "Business", "Luxury", "Minimal", "Cool", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Professional",
    placeholder: "e.g. synergy, crest",
    resultLabel: "Business Name",
    generateButtonText: "Generate 50 Business Names"
  },
  {
    id: "startup-name",
    name: "Startup Name Generator",
    path: "/startup-name-generator",
    description: "Discover modern, catchy, and trademark-friendly startup name formulas.",
    icon: Rocket,
    platforms: ["Universal", "AI", "SaaS", "Fintech", "Health", "E-commerce", "Crypto"],
    styles: ["Minimal", "Cool", "Professional", "Business", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Minimal",
    placeholder: "e.g. apex, cloud",
    resultLabel: "Startup Name",
    generateButtonText: "Generate 50 Startup Names"
  },
  {
    id: "company-name",
    name: "Company Name Generator",
    path: "/company-name-generator",
    description: "Find structured, trustworthy, and scalable company names for any industry.",
    icon: Building2,
    platforms: ["Universal", "Agency", "Consultancy", "Tech", "Finance", "Logistics", "Creative"],
    styles: ["Professional", "Business", "Luxury", "Minimal", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Professional",
    placeholder: "e.g. summit, alpha",
    resultLabel: "Company Name",
    generateButtonText: "Generate 50 Company Names"
  },
  {
    id: "team-name",
    name: "Team Name Generator",
    path: "/team-name-generator",
    description: "Get cool, creative, and motivating names for corporate, sports, or trivia teams.",
    icon: Users,
    platforms: ["Universal", "Corporate", "Creative", "Sports", "Fitness", "Trivia", "Gaming"],
    styles: ["Cool", "Funny", "Dark", "Professional", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Cool",
    placeholder: "e.g. eagles, elite",
    resultLabel: "Team Name",
    generateButtonText: "Generate 50 Team Names"
  },
  {
    id: "clan-name",
    name: "Clan Name Generator",
    path: "/clan-name-generator",
    description: "Build legendary clan names for FPS, RPG, and competitive gaming squads.",
    icon: Shield,
    platforms: ["Universal", "Competitive", "FPS", "RPG", "Fantasy", "Cool", "Dark"],
    styles: ["Gaming", "Dark", "Cool", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Gaming",
    placeholder: "e.g. storm, viper",
    resultLabel: "Clan Name",
    generateButtonText: "Generate 50 Clan Names"
  },
  {
    id: "guild-name",
    name: "Guild Name Generator",
    path: "/guild-name-generator",
    description: "Forge epic, medieval, or fantasy guild names for MMOs and cooperative gaming.",
    icon: Crown,
    platforms: ["Universal", "MMO", "RPG", "Fantasy", "Medieval", "Badass", "Cozy"],
    styles: ["Gaming", "Dark", "Luxury", "Cool", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Gaming",
    placeholder: "e.g. eon, templar",
    resultLabel: "Guild Name",
    generateButtonText: "Generate 50 Guild Names"
  },
  {
    id: "gamertag",
    name: "Gamertag Generator",
    path: "/gamertag-generator",
    description: "Create aggressive, sleek, or futuristic Xbox and PlayStation gamertags.",
    icon: Gamepad2,
    platforms: ["Universal", "Xbox", "PlayStation", "Steam", "Nintendo", "Esports", "Gaming"],
    styles: ["Gaming", "Cool", "Dark", "Funny", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Gaming",
    placeholder: "e.g. nexus, bullet",
    resultLabel: "Gamertag",
    generateButtonText: "Generate 50 Gamertags"
  },
  {
    id: "fantasy-name",
    name: "Fantasy Name Generator",
    path: "/fantasy-name-generator",
    description: "Generate mythical, ancient, and heroic names for roleplaying and worldbuilding.",
    icon: Flame,
    platforms: ["Universal", "MMO", "RPG", "Fantasy", "Medieval", "D&D"],
    styles: ["Cool", "Dark", "Aesthetic", "Luxury", "Random"],
    defaultPlatform: "Fantasy",
    defaultStyle: "Cool",
    placeholder: "e.g. eldon, valeria",
    resultLabel: "Fantasy Name",
    generateButtonText: "Generate 50 Fantasy Names"
  },
  {
    id: "character-name",
    name: "Character Name Generator",
    path: "/character-name-generator",
    description: "Find the perfect name for your novel, script, screenplay, or game protagonist.",
    icon: User,
    platforms: ["Universal", "Fiction", "Screenplay", "Gaming", "Historical", "Sci-Fi"],
    styles: ["Cool", "Aesthetic", "Minimal", "Luxury", "Dark", "Cute", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Cool",
    placeholder: "e.g. arthur, selene",
    resultLabel: "Character Name",
    generateButtonText: "Generate 50 Character Names"
  },
  {
    id: "ai-name",
    name: "AI Name Generator",
    path: "/ai-name-generator",
    description: "Generate futuristic, high-tech, and intelligent names for bots, AIs, and systems.",
    icon: Cpu,
    platforms: ["Universal", "AI", "SaaS", "Cybernetics", "Neural Net", "Robotics"],
    styles: ["Minimal", "Cool", "Professional", "Business", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Minimal",
    placeholder: "e.g. cortex, synapse",
    resultLabel: "AI Name",
    generateButtonText: "Generate 50 AI Names"
  },
  {
    id: "baby-name",
    name: "Baby Name Generator",
    path: "/baby-name-generator",
    description: "Discover beautiful, traditional, and modern baby names for boys and girls.",
    icon: Heart,
    platforms: ["Universal", "Cute", "Traditional", "Modern", "Unique", "Floral"],
    styles: ["Cute", "Aesthetic", "Minimal", "Luxury", "Random"],
    defaultPlatform: "Baby Nicknames",
    defaultStyle: "Cute",
    placeholder: "e.g. liam, olivia",
    resultLabel: "Baby Name",
    generateButtonText: "Generate 50 Baby Names"
  },
  {
    id: "pet-name",
    name: "Pet Name Generator",
    path: "/pet-name-generator",
    description: "Find cute, funny, or majestic names for your dogs, cats, birds, and other pets.",
    icon: Heart,
    platforms: ["Universal", "Dog", "Cat", "Bird", "Cute", "Majestic"],
    styles: ["Cute", "Funny", "Cool", "Minimal", "Random"],
    defaultPlatform: "Pet Names",
    defaultStyle: "Cute",
    placeholder: "e.g. max, luna",
    resultLabel: "Pet Name",
    generateButtonText: "Generate 50 Pet Names"
  },
  {
    id: "domain-name",
    name: "Domain Name Generator",
    path: "/domain-name-generator",
    description: "Create brandable, memorable, and available .com domain name ideas instantly.",
    icon: Globe,
    platforms: ["Universal", "Tech", "SaaS", "E-commerce", "Blog", "Creative"],
    styles: ["Minimal", "Cool", "Professional", "Business", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Minimal",
    placeholder: "e.g. flow, sync",
    resultLabel: "Domain Name",
    generateButtonText: "Generate 50 Domain Names"
  },
  {
    id: "podcast-name",
    name: "Podcast Name Generator",
    path: "/podcast-name-generator",
    description: "Brainstorm high-impact, catchy, and conversational podcast show title ideas.",
    icon: Mic,
    platforms: ["Universal", "Apple Podcasts", "Spotify", "Comedy", "Business", "True Crime"],
    styles: ["Cool", "Funny", "Professional", "Aesthetic", "Random"],
    defaultPlatform: "Podcast Name",
    defaultStyle: "Cool",
    placeholder: "e.g. chat, frequency",
    resultLabel: "Podcast Name",
    generateButtonText: "Generate 50 Podcast Names"
  },
  {
    id: "store-name",
    name: "Store Name Generator",
    path: "/store-name-generator",
    description: "Find unique, modern, and high-conversion names for retail shops and e-commerce stores.",
    icon: Store,
    platforms: ["Universal", "E-commerce", "Retail", "Boutique", "Vintage", "Modern"],
    styles: ["Minimal", "Luxury", "Cool", "Professional", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Minimal",
    placeholder: "e.g. craft, apex",
    resultLabel: "Store Name",
    generateButtonText: "Generate 50 Store Names"
  },
  {
    id: "restaurant-name",
    name: "Restaurant Name Generator",
    path: "/restaurant-name-generator",
    description: "Generate appetizing, elegant, and catchy names for eateries and bistros.",
    icon: Utensils,
    platforms: ["Universal", "Bistro", "Fine Dining", "Fast Casual", "Cafe", "Tavern"],
    styles: ["Luxury", "Aesthetic", "Professional", "Cool", "Random"],
    defaultPlatform: "Restaurant Name",
    defaultStyle: "Luxury",
    placeholder: "e.g. table, hearth",
    resultLabel: "Restaurant Name",
    generateButtonText: "Generate 50 Restaurant Names"
  },
  {
    id: "cafe-name",
    name: "Cafe Name Generator",
    path: "/cafe-name-generator",
    description: "Create cozy, aesthetic, and charming name ideas for your coffee shop or roastery.",
    icon: Coffee,
    platforms: ["Universal", "Espresso", "Bistro", "Roastery", "Teahouse", "Bakery"],
    styles: ["Aesthetic", "Minimal", "Cool", "Cute", "Random"],
    defaultPlatform: "Cafe Name",
    defaultStyle: "Aesthetic",
    placeholder: "e.g. grind, brew",
    resultLabel: "Cafe Name",
    generateButtonText: "Generate 50 Cafe Names"
  },
  {
    id: "book-title",
    name: "Book Title Generator",
    path: "/book-title-generator",
    description: "Find compelling, atmospheric, and bestselling title ideas for your next book.",
    icon: BookOpen,
    platforms: ["Universal", "Fiction", "Non-Fiction", "Mystery", "Romance", "Fantasy", "Sci-Fi"],
    styles: ["Aesthetic", "Cool", "Dark", "Luxury", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Aesthetic",
    placeholder: "e.g. chronicle, whisper",
    resultLabel: "Book Title",
    generateButtonText: "Generate 50 Book Titles"
  },
  {
    id: "song-name",
    name: "Song Name Generator",
    path: "/song-name-generator",
    description: "Discover deep, lyrical, and poetic title ideas for your songs and tracks.",
    icon: Music,
    platforms: ["Universal", "Pop", "Rock", "Hip Hop", "Indie", "Electronic", "Acoustic"],
    styles: ["Aesthetic", "Dark", "Cool", "Funny", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Aesthetic",
    placeholder: "e.g. echo, velvet",
    resultLabel: "Song Name",
    generateButtonText: "Generate 50 Song Names"
  },
  {
    id: "band-name",
    name: "Band Name Generator",
    path: "/band-name-generator",
    description: "Generate badass, classic, or alternative band name ideas for your music group.",
    icon: Music,
    platforms: ["Universal", "Rock", "Indie", "Metal", "Pop", "Jazz", "Electronic"],
    styles: ["Cool", "Dark", "Funny", "Aesthetic", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Cool",
    placeholder: "e.g. vortex, echo",
    resultLabel: "Band Name",
    generateButtonText: "Generate 50 Band Names"
  },
  {
    id: "project-name",
    name: "Project Name Generator",
    path: "/project-name-generator",
    description: "Create catchy, structured, and modern code names for projects and campaigns.",
    icon: Terminal,
    platforms: ["Universal", "Tech", "Business", "Creative", "Internal", "Secret"],
    styles: ["Minimal", "Cool", "Professional", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Minimal",
    placeholder: "e.g. apex, vortex",
    resultLabel: "Project Name",
    generateButtonText: "Generate 50 Project Names"
  },
  {
    id: "app-name",
    name: "App Name Generator",
    path: "/app-name-generator",
    description: "Discover sleek, viral, and brandable name ideas for your mobile or web app.",
    icon: Terminal,
    platforms: ["Universal", "iOS", "Android", "SaaS", "Utility", "Game"],
    styles: ["Minimal", "Cool", "Professional", "Business", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Minimal",
    placeholder: "e.g. flow, peak",
    resultLabel: "App Name",
    generateButtonText: "Generate 50 App Names"
  },
  {
    id: "product-name",
    name: "Product Name Generator",
    path: "/product-name-generator",
    description: "Create memorable, brandable, and commercial names for physical or digital products.",
    icon: Terminal,
    platforms: ["Universal", "SaaS", "Hardware", "Consumer Goods", "B2B", "Digital"],
    styles: ["Minimal", "Luxury", "Cool", "Professional", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Minimal",
    placeholder: "e.g. prime, core",
    resultLabel: "Product Name",
    generateButtonText: "Generate 50 Product Names"
  },
  {
    id: "kingdom-name",
    name: "Kingdom Name Generator",
    path: "/kingdom-name-generator",
    description: "Forge majestic, ancient, and historical empire and kingdom names for fantasy.",
    icon: Compass,
    platforms: ["Universal", "Fantasy", "Historical", "RPG", "Medieval", "Conquest"],
    styles: ["Luxury", "Dark", "Cool", "Gaming", "Random"],
    defaultPlatform: "Fantasy",
    defaultStyle: "Luxury",
    placeholder: "e.g. elysia, valoria",
    resultLabel: "Kingdom Name",
    generateButtonText: "Generate 50 Kingdom Names"
  },
  {
    id: "city-name",
    name: "City Name Generator",
    path: "/city-name-generator",
    description: "Find beautiful, realistic, or historical city name ideas for your world map.",
    icon: MapPin,
    platforms: ["Universal", "Modern", "Historical", "Fantasy", "Sci-Fi", "RPG"],
    styles: ["Cool", "Minimal", "Aesthetic", "Dark", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Cool",
    placeholder: "e.g. haven, summit",
    resultLabel: "City Name",
    generateButtonText: "Generate 50 City Names"
  },
  {
    id: "planet-name",
    name: "Planet Name Generator",
    path: "/planet-name-generator",
    description: "Discover futuristic, galactic, and celestial planet and star names for sci-fi.",
    icon: Globe,
    platforms: ["Universal", "Sci-Fi", "Astronomy", "Fantasy", "RPG", "Cosmic"],
    styles: ["Cool", "Dark", "Minimal", "Luxury", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Cool",
    placeholder: "e.g. nova, orbit",
    resultLabel: "Planet Name",
    generateButtonText: "Generate 50 Planet Names"
  },
  {
    id: "blog-name",
    name: "Blog Name Generator",
    path: "/blog-name-generator",
    description: "Find high-retention, niche-friendly, and catchy names for your next blog.",
    icon: BookOpen,
    platforms: ["Universal", "Lifestyle", "Tech", "Travel", "Food", "Fashion", "Finance"],
    styles: ["Aesthetic", "Minimal", "Cool", "Professional", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Aesthetic",
    placeholder: "e.g. diary, journal",
    resultLabel: "Blog Name",
    generateButtonText: "Generate 50 Blog Names"
  },
  {
    id: "youtube-channel-name",
    name: "YouTube Channel Name Generator",
    path: "/youtube-channel-names",
    description: "Find professional, highly searchable, and creative YouTube channel names.",
    icon: Tv,
    platforms: ["Universal", "Gaming", "Vlogs", "Tech", "Review", "Educational", "Shorts"],
    styles: ["Cool", "Professional", "Funny", "Aesthetic", "Random"],
    defaultPlatform: "YouTube",
    defaultStyle: "Cool",
    placeholder: "e.g. lens, show",
    resultLabel: "YouTube Name",
    generateButtonText: "Generate 50 YouTube Names"
  },
  {
    id: "twitch-name",
    name: "Twitch Name Generator",
    path: "/twitch-name-generator",
    description: "Generate highly engaging, brandable, and live-ready streaming usernames.",
    icon: Radio,
    platforms: ["Universal", "Gaming", "Esports", "Variety", "Creative", "Just Chatting"],
    styles: ["Gaming", "Cool", "Dark", "Funny", "Random"],
    defaultPlatform: "Twitch",
    defaultStyle: "Gaming",
    placeholder: "e.g. plays, live",
    resultLabel: "Twitch Name",
    generateButtonText: "Generate 50 Twitch Names"
  },
  {
    id: "instagram-username",
    name: "Instagram Username Generator",
    path: "/instagram-username-generator",
    description: "Create clean, aesthetic, and eye-catching Instagram handles to boost followers.",
    icon: Hash,
    platforms: ["Universal", "Instagram", "Fashion", "Travel", "Creator", "Business"],
    styles: ["Aesthetic", "Minimal", "Cool", "Luxury", "Random"],
    defaultPlatform: "Instagram",
    defaultStyle: "Aesthetic",
    placeholder: "e.g. grid, fits",
    resultLabel: "Instagram Handle",
    generateButtonText: "Generate 50 Instagram Handles"
  },
  {
    id: "tiktok-username",
    name: "TikTok Username Generator",
    path: "/tiktok-username-generator",
    description: "Discover viral, high-energy, and catchy TikTok usernames for the FYP.",
    icon: Hash,
    platforms: ["Universal", "TikTok", "Short-Form", "Vibe", "Dance", "Comedy"],
    styles: ["Cool", "Funny", "Aesthetic", "Cute", "Random"],
    defaultPlatform: "TikTok",
    defaultStyle: "Cool",
    placeholder: "e.g. loop, hook",
    resultLabel: "TikTok Handle",
    generateButtonText: "Generate 50 TikTok Handles"
  },
  {
    id: "discord-username",
    name: "Discord Username Generator",
    path: "/discord-usernames",
    description: "Create chill, community-friendly, and modern Discord handles.",
    icon: Hash,
    platforms: ["Universal", "Discord", "Gaming", "Anime", "Lounge", "Social"],
    styles: ["Cool", "Aesthetic", "Funny", "Cute", "Random"],
    defaultPlatform: "Discord",
    defaultStyle: "Cool",
    placeholder: "e.g. chat, server",
    resultLabel: "Discord Handle",
    generateButtonText: "Generate 50 Discord Handles"
  },
  {
    id: "roblox-username",
    name: "Roblox Username Generator",
    path: "/roblox-usernames",
    description: "Create unique, platform-compliant, and cute Roblox usernames instantly.",
    icon: Hash,
    platforms: ["Universal", "Roblox", "Gaming", "Roleplay", "Obby", "Dev"],
    styles: ["Cute", "Cool", "Funny", "Gaming", "Random"],
    defaultPlatform: "Roblox",
    defaultStyle: "Cute",
    placeholder: "e.g. build, block",
    resultLabel: "Roblox Handle",
    generateButtonText: "Generate 50 Roblox Handles"
  },
  {
    id: "minecraft-username",
    name: "Minecraft Username Generator",
    path: "/minecraft-usernames",
    description: "Find rare, clean, and OG Minecraft username ideas for servers and realms.",
    icon: Hash,
    platforms: ["Universal", "Minecraft", "PvP", "Survival", "Factions", "Creative"],
    styles: ["Gaming", "Cool", "Cute", "Dark", "Random"],
    defaultPlatform: "Minecraft",
    defaultStyle: "Gaming",
    placeholder: "e.g. block, craft",
    resultLabel: "Minecraft Handle",
    generateButtonText: "Generate 50 Minecraft Handles"
  },
  {
    id: "fortnite-username",
    name: "Fortnite Username Generator",
    path: "/fortnite-usernames",
    description: "Generate sweaty, competitive, and legendary Fortnite names to dominate the lobby.",
    icon: Hash,
    platforms: ["Universal", "Fortnite", "Battle Royale", "Arena", "Squad", "Esports"],
    styles: ["Gaming", "Cool", "Dark", "Funny", "Random"],
    defaultPlatform: "Fortnite",
    defaultStyle: "Gaming",
    placeholder: "e.g. edit, clutch",
    resultLabel: "Fortnite Handle",
    generateButtonText: "Generate 50 Fortnite Handles"
  },
  {
    id: "valorant-username",
    name: "Valorant Username Generator",
    path: "/valorant-usernames",
    description: "Create tactical, agent-specific, and precise Valorant usernames.",
    icon: Hash,
    platforms: ["Universal", "Valorant", "Tactical FPS", "Esports", "Ranked", "Duo"],
    styles: ["Gaming", "Cool", "Dark", "Professional", "Random"],
    defaultPlatform: "Valorant",
    defaultStyle: "Gaming",
    placeholder: "e.g. agent, clutch",
    resultLabel: "Valorant Handle",
    generateButtonText: "Generate 50 Valorant Handles"
  },
  {
    id: "steam-username",
    name: "Steam Username Generator",
    path: "/steam-usernames",
    description: "Engineer rare, completionist, and aesthetic Steam profile usernames.",
    icon: Hash,
    platforms: ["Universal", "Steam", "PC Gaming", "Library", "Community", "Modder"],
    styles: ["Cool", "Aesthetic", "Minimal", "Dark", "Random"],
    defaultPlatform: "Steam",
    defaultStyle: "Cool",
    placeholder: "e.g. game, profile",
    resultLabel: "Steam Handle",
    generateButtonText: "Generate 50 Steam Handles"
  },
  {
    id: "xbox-gamertag",
    name: "Xbox Gamertag Generator",
    path: "/xbox-gamertags",
    description: "Discover classic, console-ready, and achievement-hunting Xbox gamertags.",
    icon: Gamepad2,
    platforms: ["Universal", "Xbox", "Console", "Live Party", "Ecosystem", "Gaming"],
    styles: ["Gaming", "Cool", "Funny", "Dark", "Random"],
    defaultPlatform: "Xbox",
    defaultStyle: "Gaming",
    placeholder: "e.g. live, controller",
    resultLabel: "Xbox Gamertag",
    generateButtonText: "Generate 50 Xbox Gamertags"
  },
  {
    id: "psn-name",
    name: "PSN Name Generator",
    path: "/psn-usernames",
    description: "Create cinematic, immersive, and trophy-hunting PlayStation Network IDs.",
    icon: Gamepad2,
    platforms: ["Universal", "PlayStation", "PSN", "Trophy Hunter", "Console", "Gaming"],
    styles: ["Gaming", "Cool", "Dark", "Luxury", "Random"],
    defaultPlatform: "PlayStation",
    defaultStyle: "Gaming",
    placeholder: "e.g. trophy, console",
    resultLabel: "PSN Name",
    generateButtonText: "Generate 50 PSN Names"
  },
  {
    id: "aesthetic-username",
    name: "Aesthetic Username Generator",
    path: "/aesthetic-usernames",
    description: "Find cozy, vaporwave, and indie aesthetic usernames for social grids.",
    icon: Smile,
    platforms: ["Universal", "Aesthetic", "Instagram", "Pinterest", "TikTok", "Social"],
    styles: ["Aesthetic", "Minimal", "Luxury", "Cute", "Random"],
    defaultPlatform: "Aesthetic",
    defaultStyle: "Aesthetic",
    placeholder: "e.g. sunset, haze",
    resultLabel: "Aesthetic Username",
    generateButtonText: "Generate 50 Aesthetic Handles"
  },
  {
    id: "cool-username",
    name: "Cool Username Generator",
    path: "/cool-usernames",
    description: "Find highly memorable, sleek, and dynamic cool usernames for profiles.",
    icon: Sparkles,
    platforms: ["Universal", "Cool", "Gaming", "Social Media", "Chat", "Creator"],
    styles: ["Cool", "Minimal", "Dark", "Luxury", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Cool",
    placeholder: "e.g. neon, vortex",
    resultLabel: "Cool Username",
    generateButtonText: "Generate 50 Cool Handles"
  },
  {
    id: "cute-username",
    name: "Cute Username Generator",
    path: "/cute-usernames",
    description: "Discover adorable, soft, and pastel-styled cute usernames for any profile.",
    icon: Smile,
    platforms: ["Universal", "Cute", "Kawaii", "Cozy Gaming", "Lifestyle", "Friends"],
    styles: ["Cute", "Aesthetic", "Funny", "Minimal", "Random"],
    defaultPlatform: "Cute",
    defaultStyle: "Cute",
    placeholder: "e.g. sweet, peach",
    resultLabel: "Cute Username",
    generateButtonText: "Generate 50 Cute Handles"
  },
  {
    id: "funny-username",
    name: "Funny Username Generator",
    path: "/funny-usernames",
    description: "Create sarcastic, punny, and hilarious funny usernames for social apps.",
    icon: Smile,
    platforms: ["Universal", "Funny", "Meme", "Comedy", "Casual Gaming", "Social"],
    styles: ["Funny", "Cool", "Dark", "Cute", "Random"],
    defaultPlatform: "Funny",
    defaultStyle: "Funny",
    placeholder: "e.g. potato, taco",
    resultLabel: "Funny Username",
    generateButtonText: "Generate 50 Funny Handles"
  },
  {
    id: "dark-username",
    name: "Dark Username Generator",
    path: "/dark-usernames",
    description: "Create gothic, mysterious, and shadowy dark usernames for profile canvases.",
    icon: User,
    platforms: ["Universal", "Dark Theme", "Gothic", "Cyberpunk", "Alternative", "Social"],
    styles: ["Dark", "Cool", "Minimal", "Luxury", "Random"],
    defaultPlatform: "Dark",
    defaultStyle: "Dark",
    placeholder: "e.g. void, midnight",
    resultLabel: "Dark Username",
    generateButtonText: "Generate 50 Dark Handles"
  },
  {
    id: "anime-username",
    name: "Anime Username Generator",
    path: "/anime-usernames",
    description: "Find epic, otaku, and aesthetic anime usernames for forums and avatars.",
    icon: Sparkles,
    platforms: ["Universal", "Anime", "Otaku", "Manga", "Discord", "Gaming"],
    styles: ["Aesthetic", "Dark", "Cool", "Cute", "Random"],
    defaultPlatform: "Anime",
    defaultStyle: "Aesthetic",
    placeholder: "e.g. spirit, aura",
    resultLabel: "Anime Username",
    generateButtonText: "Generate 50 Anime Handles"
  },
  {
    id: "superhero-name",
    name: "Superhero Name Generator",
    path: "/superhero-name-generator",
    description: "Create legendary, heroic, and inspiring superhero names for comics and RPGs.",
    icon: Sword,
    platforms: ["Universal", "Heroic", "Comics", "RPG", "Fantasy", "Sci-Fi"],
    styles: ["Cool", "Luxury", "Minimal", "Gaming", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Cool",
    placeholder: "e.g. shadow, titan",
    resultLabel: "Superhero Name",
    generateButtonText: "Generate 50 Superhero Names"
  },
  {
    id: "villain-name",
    name: "Villain Name Generator",
    path: "/villain-name-generator",
    description: "Generate dark, threatening, and ruthless villain names for your villains.",
    icon: Sword,
    platforms: ["Universal", "Villainous", "Comics", "RPG", "Dark Theme", "Sci-Fi"],
    styles: ["Dark", "Cool", "Gaming", "Luxury", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Dark",
    placeholder: "e.g. doom, bane",
    resultLabel: "Villain Name",
    generateButtonText: "Generate 50 Villain Names"
  },
  {
    id: "wizard-name",
    name: "Wizard Name Generator",
    path: "/wizard-name-generator",
    description: "Forge legendary, ancient, and spellbinding wizard names for fantasy RPGs.",
    icon: Flame,
    platforms: ["Universal", "Fantasy", "Arcane", "RPG", "Spellbook", "Medieval"],
    styles: ["Gaming", "Dark", "Cool", "Luxury", "Random"],
    defaultPlatform: "Fantasy",
    defaultStyle: "Gaming",
    placeholder: "e.g. merlin, arcane",
    resultLabel: "Wizard Name",
    generateButtonText: "Generate 50 Wizard Names"
  },
  {
    id: "elf-name",
    name: "Elf Name Generator",
    path: "/elf-name-generator",
    description: "Find beautiful, ethereal, and ancient elven names for tabletop gaming.",
    icon: Flame,
    platforms: ["Universal", "Elven", "Fantasy", "RPG", "Ethereal", "Lore"],
    styles: ["Aesthetic", "Luxury", "Cool", "Minimal", "Random"],
    defaultPlatform: "Fantasy",
    defaultStyle: "Aesthetic",
    placeholder: "e.g. legolas, selene",
    resultLabel: "Elf Name",
    generateButtonText: "Generate 50 Elf Names"
  },
  {
    id: "dwarf-name",
    name: "Dwarf Name Generator",
    path: "/dwarf-name-generator",
    description: "Forge robust, historical, and mineral-toned dwarven names for RPG clans.",
    icon: Flame,
    platforms: ["Universal", "Dwarven", "Fantasy", "RPG", "Mining", "Clan"],
    styles: ["Gaming", "Dark", "Cool", "Professional", "Random"],
    defaultPlatform: "Fantasy",
    defaultStyle: "Gaming",
    placeholder: "e.g. thorin, onyx",
    resultLabel: "Dwarf Name",
    generateButtonText: "Generate 50 Dwarf Names"
  },
  {
    id: "dragon-name",
    name: "Dragon Name Generator",
    path: "/dragon-name-generator",
    description: "Create aggressive, legendary, and fiery dragon names for fantasy lore.",
    icon: Flame,
    platforms: ["Universal", "Dragon", "Fantasy", "RPG", "Lethal", "Ancient"],
    styles: ["Gaming", "Dark", "Cool", "Luxury", "Random"],
    defaultPlatform: "Fantasy",
    defaultStyle: "Gaming",
    placeholder: "e.g. smaug, viper",
    resultLabel: "Dragon Name",
    generateButtonText: "Generate 50 Dragon Names"
  },
  {
    id: "ship-name",
    name: "Ship Name Generator",
    path: "/ship-name-generator",
    description: "Find romantic, historic, and majestic name ideas for vessels and boats.",
    icon: Compass,
    platforms: ["Universal", "Maritime", "Historic", "RPG", "Navy", "Fantasy"],
    styles: ["Luxury", "Aesthetic", "Cool", "Professional", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Luxury",
    placeholder: "e.g. voyager, crest",
    resultLabel: "Ship Name",
    generateButtonText: "Generate 50 Ship Names"
  },
  {
    id: "spaceship-name",
    name: "Spaceship Name Generator",
    path: "/spaceship-name-generator",
    description: "Discover futuristic, high-tech, and stellar spaceship names for sci-fi.",
    icon: Globe,
    platforms: ["Universal", "Sci-Fi", "Cosmic", "RPG", "Ecosystem", "Navy"],
    styles: ["Cool", "Minimal", "Dark", "Luxury", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Cool",
    placeholder: "e.g. odyssey, apex",
    resultLabel: "Spaceship Name",
    generateButtonText: "Generate 50 Spaceship Names"
  },
  {
    id: "weapon-name",
    name: "Weapon Name Generator",
    path: "/weapon-name-generator",
    description: "Forge lethal, epic, and ancient name ideas for swords, daggers, and weapons.",
    icon: Sword,
    platforms: ["Universal", "RPG", "Fantasy", "Lethal", "Historic", "Modern"],
    styles: ["Gaming", "Dark", "Cool", "Luxury", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Gaming",
    placeholder: "e.g. scythe, blade",
    resultLabel: "Weapon Name",
    generateButtonText: "Generate 50 Weapon Names"
  },
  {
    id: "club-name",
    name: "Club Name Generator",
    path: "/club-name-generator",
    description: "Generate creative, motivating, and exclusive club name ideas for groups.",
    icon: Users,
    platforms: ["Universal", "Social", "Creative", "Sports", "Fitness", "Interest"],
    styles: ["Cool", "Funny", "Professional", "Aesthetic", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Cool",
    placeholder: "e.g. guild, collective",
    resultLabel: "Club Name",
    generateButtonText: "Generate 50 Club Names"
  },
  {
    id: "boutique-name",
    name: "Boutique Name Generator",
    path: "/boutique-name-generator",
    description: "Create premium, charming, and elegant boutique names for fashion shops.",
    icon: Shirt,
    platforms: ["Universal", "Fashion", "Boutique", "Couture", "Vintage", "Modern"],
    styles: ["Luxury", "Aesthetic", "Minimal", "Cool", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Luxury",
    placeholder: "e.g. atelier, velvet",
    resultLabel: "Boutique Name",
    generateButtonText: "Generate 50 Boutique Names"
  },
  {
    id: "agency-name",
    name: "Agency Name Generator",
    path: "/agency-name-generator",
    description: "Create highly professional, modern, and trustworthy naming ideas for agencies.",
    icon: Building2,
    platforms: ["Universal", "Creative", "Marketing", "Consulting", "Digital", "Design"],
    styles: ["Professional", "Business", "Minimal", "Cool", "Random"],
    defaultPlatform: "Universal",
    defaultStyle: "Professional",
    placeholder: "e.g. synergy, beacon",
    resultLabel: "Agency Name",
    generateButtonText: "Generate 50 Agency Names"
  }
];

// Helper to find the matching tool configuration for a given path/URL
export function getToolForPath(path: string): ToolConfig {
  // Direct match check first
  const directMatch = tools.find((t) => t.path === path);
  if (directMatch) return directMatch;

  // Pattern checks (e.g. sub-paths)
  const lowerPath = path.toLowerCase();
  
  if (lowerPath.includes("display-name")) {
    return tools.find((t) => t.id === "display-name") || tools[0];
  }
  if (lowerPath.includes("nickname") || lowerPath.includes("baby-nickname")) {
    return tools.find((t) => t.id === "nickname") || tools[0];
  }
  if (lowerPath.includes("brand-name")) {
    return tools.find((t) => t.id === "brand-name") || tools[0];
  }
  if (lowerPath.includes("business-name") || lowerPath.includes("business-usernames") || lowerPath.includes("business-brand-names") || lowerPath.includes("business-agency-names")) {
    return tools.find((t) => t.id === "business-name") || tools[0];
  }
  if (lowerPath.includes("startup-name") || lowerPath.includes("startup-")) {
    return tools.find((t) => t.id === "startup-name") || tools[0];
  }
  if (lowerPath.includes("company-name") || lowerPath.includes("company-")) {
    return tools.find((t) => t.id === "company-name") || tools[0];
  }
  if (lowerPath.includes("team-name") || lowerPath.includes("team-")) {
    return tools.find((t) => t.id === "team-name") || tools[0];
  }
  if (lowerPath.includes("clan-name") || lowerPath.includes("clan-")) {
    return tools.find((t) => t.id === "clan-name") || tools[0];
  }
  if (lowerPath.includes("guild-name") || lowerPath.includes("guild-")) {
    return tools.find((t) => t.id === "guild-name") || tools[0];
  }
  if (lowerPath.includes("gamertag") || lowerPath.includes("xbox") || lowerPath.includes("psn")) {
    return tools.find((t) => t.id === "gamertag") || tools[0];
  }

  // Default fallback to Tool #1 (Username Generator)
  return tools[0];
}
